<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Agent\LiaraDocsAssistant.Agent.csproj" />
    <ProjectReference Include="..\Data\LiaraDocsAssistant.Data.csproj" />
    <ProjectReference Include="..\Ingestion\LiaraDocsAssistant.Ingestion.csproj" />
    <ProjectReference Include="..\Retrieval\LiaraDocsAssistant.Retrieval.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

</Project>
